[workspace]
members = [
  "crates/pivotal-tracker",
  "crates/pivotal-tracker-derive",
  "crates/story-tracker-cli",
]
resolver = "2"

[workspace.metadata.release]
tag-name = "{{crate_name}}@{{version}}"
