version: 2.1

orbs:
  nix: eld/nix@1.1.1

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - nix/install
      - run: sudo chown -R circleci:circleci /nix
      - nix/install-cachix
      - run: nix profile install --accept-flake-config nixpkgs#devenv
      - run: sudo apt-get update && apt-get install -y libssl-dev
      - run: devenv test

workflows:
  default:
    jobs:
      - test
