version: 2.1

orbs:
  nix: eld/nix@1.1.1 # test

jobs:
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - nix/install
      - nix/install-cachix
      - run: nix profile install --accept-flake-config nixpkgs#devenv
      - run: devenv test

workflows:
  default:
    jobs:
      - test
