version: 2.1

orbs:
  nix: eld/nix@1.1.1

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - nix/install
      - run: sudo chown -R circleci:circleci /nix
      - restore_cache:
          keys:
            - &devenv-cache devenv-v1-{{ checksum "devenv.lock" }}
            - devenv-v1-
            - devenv-v
      - nix/install-cachix
      - run: nix profile install --accept-flake-config nixpkgs#devenv
      - save_cache:
          paths:
            - /nix
          key: *devenv-cache
      - restore_cache:
          keys:
            - &cargo-cache cargo-v1-{{ checksum "Cargo.lock" }}
            - cargo-v1-
            - cargo-v
      - run: devenv shell cargo build
      - save_cache:
          paths:
            - ~/.cargo
            - target
          key: *cargo-cache
      - run: devenv test

workflows:
  default:
    jobs:
      - test:
          context:
            - pivotal-tracker
