version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: sh <(curl -L https://nixos.org/nix/install) --no-daemon
      - run: sudo chown -R circleci:circleci /nix
      - run: nix profile install github:nixos/nixpkgs/nixpkgs-unstable#cachix
      - run: nix profile install --accept-flake-config nixpkgs#devenv
      - run: devenv test

workflows:
  default:
    jobs:
      - test
