[package]
name = "story-tracker-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stb"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auth-git2 = "0.5.4"
clap = { version = "4.4.18", features = ["derive"] }
git2 = "0.18.0"
pivotal-tracker = { version = "*", path = "../pivotal-tracker" }
serde = "1.0.144"
serde_json = "1.0.108"
slug = "0.1.4"
tokio = { version = "1.21.0", features = ["full"] }
