[package]
name = "pivotal-tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
pivotal-tracker-derive = { path = "../pivotal-tracker-derive" }
regex = "1.10.2"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.21.0", features = ["full"] }
url = { version = "2.4.1", features = ["serde"] }
