[package]
name = "story-tracker-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pivotal_tracker = { version = "*", path = "../pivotal_tracker" }
tokio = { version = "1.18.2", features = ["full"] }
